!obj:pylearn2.train.Train {
    dataset: &train !obj:practice_dataset.PracticeDataset {
        which_set: 'train',
        start: 0,
        stop: %(train_stop)i
    },

    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                 #!obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: %(dim_h0)i,
                     sparse_init: 2,
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 3,
                     irange: 0.
                 }
                ],
        nvis: 4,
    },

    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 20,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        updates_per_batch: 10,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:practice_dataset.PracticeDataset {
                              which_set: 'train',
                              start: %(train_stop)i,
                              stop: %(valid_stop)i
                          },
                'test'  : !obj:practice_dataset.PracticeDataset {
                              which_set: 'test',
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass"
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: %(max_epochs)i
                }
            ]
        }
    },

    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s/mlp_best.pkl"
        },
    ]

}